# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "usbhid" "sdhci_pci"];
      kernelModules = ["amdgpu"];
    };
    # Restore critical network drivers (Realtek 2.5G Ethernet + MediaTek WiFi)
    kernelModules = ["kvm-amd" "mt7925e" "r8125"];
    extraModulePackages = with config.boot.kernelPackages; [r8125];
  };

  # Required for WiFi/Bluetooth hardware
  hardware.enableRedistributableFirmware = true;

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/0b629b65-a1b7-40df-a7dc-9ea5e0b04959";
      fsType = "btrfs";
      options = ["subvol=@" "compress=zstd" "noatime"];
    };
    "/data" = {
      device = "/dev/disk/by-uuid/046ea663-da55-48b7-b516-0dcdb87ba710";
      fsType = "btrfs";
      options = ["compress=zstd:3" "noatime" "ssd" "discard=async" "space_cache=v2" "nofail"];
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/80A3-73A9";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };
    "/rust-cache" = {
      device = "/dev/disk/by-partlabel/rust-cache";
      fsType = "ext4";
      options = ["noatime" "discard=async"];
    };
  };

  # Disk swap dropped — zramSwap (10% of 64G = ~6.4G compressed) is sufficient.
  # Freed 10G from p2. See boot.nix for zramSwap config.

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
