# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
let
  mkFilesystem = import ../../../lib/filesystems.nix lib;
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "thunderbolt"
        "usbhid"
        "sdhci_pci"
      ];
      kernelModules = [ "amdgpu" ];
    };
    # Restore critical network drivers (Realtek 2.5G Ethernet + MediaTek WiFi)
    kernelModules = [
      "kvm-amd"
      "mt7925e"
      "r8125"
    ];
    extraModulePackages = with config.boot.kernelPackages; [ r8125 ];
  };

  # Required for WiFi/Bluetooth hardware
  hardware.enableRedistributableFirmware = true;

  fileSystems = {
    # Explicitly disable continuous async TRIM (nodiscard).
    # QLC NAND (Lexar NQ790) has 253ms discard latency → BTRFS commit stalls.
    # Periodic fstrim (configuration.nix, daily, idle priority) handles TRIM without competing with host I/O.
    # nodiscard is set explicitly for defense-in-depth: makes intent clear and guards
    # against any future kernel default that might enable continuous discard.
    # Note: BTRFS auto-adds the 'ssd' option for non-rotational devices, but does NOT
    # auto-enable discard. Verified on kernel 7.1.5 via sysfs discard counters (static
    # discardable_extents confirm worker is stopped when nodiscard is applied).
    "/" = mkFilesystem {
      device = "/dev/disk/by-uuid/0b629b65-a1b7-40df-a7dc-9ea5e0b04959";
      fsType = "btrfs";
      options = [
        "subvol=@"
        "compress=zstd"
        "noatime"
        "nodiscard"
        "space_cache=v2"
        # Commit every 5 min instead of the default 30s. Reduces metadata
        # write frequency ~10x on QLC NAND, preserving SLC cache blocks for
        # foreground I/O. Data loss window on crash: 5 min (acceptable with
        # daily btrbk snapshots + CoW journaling consistency).
        "commit=300"
      ];
    };
    "/data" = mkFilesystem {
      device = "/dev/disk/by-uuid/046ea663-da55-48b7-b516-0dcdb87ba710";
      fsType = "btrfs";
      options = [
        "compress=zstd:3"
        "noatime"
        "ssd"
        "nodiscard"
        "space_cache=v2"
        "nofail"
        "commit=300"
      ];
    };
    "/boot" = mkFilesystem {
      device = "/dev/disk/by-uuid/80A3-73A9";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };
    # Mirrored BTRFS pool (data+metadata raid1) on the two recovered Toshiba
    # MG08ACA16TE 16TB HDDs (USB DAS, created 2026-08-16 from the dead
    # private-cloud box). Either member by-id mounts the fs. Layout:
    # services/<name> (per-service snapshottable subvols), backups/ (btrbk
    # receive target from NVMe @ + /data), archive/ (forensics + cold data).
    # Members: ata-TOSHIBA_MG08ACA16TE_72U0A005FWTG +
    #          ata-TOSHIBA_MG08ACA16TE_72U0A0ZUFWTG (serials 72U0A005FWTG/72U0A0ZUFWTG)
    "/mnt/pool" = mkFilesystem {
      device = "/dev/disk/by-id/ata-TOSHIBA_MG08ACA16TE_72U0A005FWTG";
      fsType = "btrfs";
      options = [
        "compress=zstd"
        "noatime"
        "space_cache=v2"
        "nodiscard"
        "nofail"
        "commit=300"
      ];
    };
    # Old /rust-cache mount (nvme0n1p9, ext4, by-partlabel/rust-cache) removed
    # 2026-08-16: Rust targets moved to /mnt/buildcache/rust + sccache. The
    # partition itself still exists (98G raw) — delete/grow requires manual
    # partition-table surgery, deliberately not automated.
  };

  # Disk swap dropped — zramSwap (10% of 64G = ~6.4G compressed) is sufficient.
  # Freed 10G from p2. See boot.nix for zramSwap config.

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
