# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
let
  mkFilesystem = import ../../../lib/filesystems.nix lib;
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "thunderbolt"
        "usbhid"
        "sdhci_pci"
      ];
      kernelModules = [ "amdgpu" ];
    };
    # Restore critical network drivers (Realtek 2.5G Ethernet + MediaTek WiFi)
    kernelModules = [
      "kvm-amd"
      "mt7925e"
      "r8125"
    ];
    extraModulePackages = with config.boot.kernelPackages; [ r8125 ];
  };

  # Required for WiFi/Bluetooth hardware
  hardware.enableRedistributableFirmware = true;

  fileSystems = {
    # ════════════════════════════════════════════════════════════════════════
    # CRITICAL: Kernel 7.1.5 BTRFS SILENTLY IGNORES `nodiscard`.
    # The fstab specifies `nodiscard` but the kernel boot log shows "turning on
    # async discard" and /proc/mounts shows neither `nodiscard` nor `discard=async`.
    # The BTRFS sysfs discard counters confirm 1.3 TiB of discards processed on `/`
    # and 252 GiB on `/data` despite this option. See `disable-nvme-discard` service
    # in boot.nix — it sets discard_max_bytes=0 at the BLOCK LAYER level (unconditional).
    # Both `nodiscard` and `discard=none` are kept here for documentation/intent;
    # the block-layer disable is the actual enforcement mechanism.
    # ════════════════════════════════════════════════════════════════════════
    #
    # QLC NAND (Lexar NQ790) has 253ms discard latency → BTRFS commit stalls.
    # Suspected root cause of data corruption on /data (2026-08-03).
    # fstrim.timer is ALSO effectively disabled by the block-layer fix.
    "/" = mkFilesystem {
      device = "/dev/disk/by-uuid/0b629b65-a1b7-40df-a7dc-9ea5e0b04959";
      fsType = "btrfs";
      options = [
        "subvol=@"
        "compress=zstd"
        "noatime"
        "discard=none"
        "nodiscard"
        "space_cache=v2"
      ];
    };
    "/data" = mkFilesystem {
      device = "/dev/disk/by-uuid/046ea663-da55-48b7-b516-0dcdb87ba710";
      fsType = "btrfs";
      options = [
        "compress=zstd:3"
        "noatime"
        "ssd"
        "discard=none"
        "nodiscard"
        "space_cache=v2"
        "nofail"
      ];
    };
    "/boot" = mkFilesystem {
      device = "/dev/disk/by-uuid/80A3-73A9";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };
    # nodiscard — defense-in-depth. fstrim (configuration.nix) covers this filesystem.
    "/rust-cache" = mkFilesystem {
      device = "/dev/disk/by-partlabel/rust-cache";
      fsType = "ext4";
      options = [
        "noatime"
        "nodiscard"
        "nofail"
        "x-systemd.automount"
        "x-systemd.idle-timeout=10min"
      ];
    };
  };

  # Disk swap dropped — zramSwap (10% of 64G = ~6.4G compressed) is sufficient.
  # Freed 10G from p2. See boot.nix for zramSwap config.

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
