# VM test for the SearXNG privacy metasearch module.
#
# Verifies the runtime risks that nix eval CANNOT check:
#   1. searx service starts (Python ASGI server + config generation)
#   2. Health endpoint responds (/healthz)
#   3. Secret key is auto-generated and persisted
#   4. Settings file is valid YAML with expected keys
#
# The DNS-gate (ExecStartPre waitDnsReady) exits 0 on timeout (degraded mode),
# so SearXNG starts even without DNS — some engines just stay disabled.
{pkgs}: let
  searxngFlakeOutput = (import ../modules/nixos/services/searxng.nix) {};
  searxngNixosModule = searxngFlakeOutput.flake.nixosModules.searxng;
in {
  name = "searxng";

  nodes.machine = {...}: {
    imports = [
      searxngNixosModule
      ./test-helpers.nix
    ];

    services.searx.enable = true;
  };

  testScript = ''
    machine.start()

    # Wait for boot to complete. The searxng-secret-key oneshot may finish
    # before or after searx-init tries to start (boot ordering race).
    # We ensure the secret key file exists, then restart the searx chain.
    machine.wait_for_unit("multi-user.target")

    # 1. Secret key was auto-generated by searxng-secret-key oneshot.
    #    Use wait_for_file since the service doesn't use RemainAfterExit.
    machine.wait_for_file("/var/lib/searxng/searxng.env")

    # 2. Restart the searx init chain now that the secret key exists.
    #    Works around a boot ordering race where searx-init can start before
    #    searxng-secret-key finishes writing the environment file.
    machine.systemctl("restart searx-init.service")
    machine.systemctl("restart searx.service")

    # 3. searx service starts — catches config generation + Python startup errors
    machine.wait_for_unit("searx.service")

    # 4. Port is open (SearXNG built-in server on port 8889)
    machine.wait_for_open_port(8889)

    # 5. Health endpoint responds
    machine.succeed("curl -sf http://localhost:8889/healthz")

    # 6. Settings file exists and contains expected configuration
    machine.succeed("test -f /run/searx/settings.yml")
    machine.succeed("grep -q 'test.local' /run/searx/settings.yml")
  '';
}
