# indexer-web — event-sourced docs index WebUI (index.home.lan).
#
# Runs upstream's indexer-web binary (github:LarsArtmann/index,
# packages.indexer-web via inputs.index.nixosModules.indexer-web): an
# always-on, event-sourced view over the project documentation state under
# ~/projects. Daily rescan timer (upstream, 86400s) + scan-on-start; the
# browsing UI is unauthenticated (/, /table, /scans, /projects/<name>,
# /changelog, /openapi.json, /metrics) and the destructive /admin/* routes
# (rescan, DLQ replay/purge, projections reset) gate on an API key.
#
#   - Binds 127.0.0.1:${ports.indexer-web} (services.indexer-web.addr). The
#     vHost is Layer 2 protected — oauth2-proxy gates external access via
#     Pocket ID; the raw port must not reach the LAN (mr-sync posture).
#   - Runs as primaryUser, NOT upstream's DynamicUser: /home/lars is 0700,
#     so a dynamic uid can never traverse the scan roots. Upstream's own
#     ProtectHome=read-only (derived from searchPaths under /home) stays.
#   - Admin API key: machine-local random (searxng-secret-key doctrine —
#     NOT sops), generated by indexer-web-secret-key and injected via
#     LoadCredential (PID 1 reads the root-owned 0600 file; the unit user
#     reads it from /run/credentials). A missing key file is a startup
#     error upstream — fail-closed, never a silently open admin surface.
#   - OTel: the binary reads its OWN env var INDEXERWEB_OTEL_ENDPOINT
#     (URL-parsed, scheme REQUIRED) for traces + metrics; the registry's
#     standard OTEL_EXPORTER_OTLP_ENDPOINT rides beside it as the house
#     contract (a noop for this binary).
{ inputs, ... }:
{
  flake.nixosModules.indexer-web =
    {
      config,
      options,
      pkgs,
      lib,
      ...
    }:
    let
      cfg = config.services.indexer-web;
      inherit (import ../../../lib/default.nix lib)
        harden
        serviceOneshotDefaults
        onFailure
        ports
        ;
      primaryUser = config.users.primaryUser or "lars";
      adminKeyPath = "/var/lib/indexer-web-keys/admin-key";
      generateAdminKey = pkgs.writeShellApplication {
        name = "indexer-web-generate-admin-key";
        runtimeInputs = [ pkgs.openssl ];
        text = ''
          key="${adminKeyPath}"
          if [ ! -s "$key" ]; then
            umask 077
            openssl rand -hex 32 > "$key"
          fi
          chmod 0600 "$key"
        '';
      };
    in
    {
      imports = [
        inputs.index.nixosModules.indexer-web
        {
          # Platform-truth catalog entry (ADR-008): unconditional — declared
          # via an inline imports module so it survives hosts that never set
          # enable (cv.nix reference shape).
          services.catalog.indexer-web = {
            subdomain = "index";
            port = ports.indexer-web;
            description = "Event-sourced docs index web view";
            healthPath = "/";
          };
        }
      ];

      config = lib.mkIf cfg.enable {
        services.indexer-web = {
          addr = "127.0.0.1:${toString ports.indexer-web}";
          searchPaths = [ "/home/${primaryUser}/projects" ];
          apiKeyFile = "/run/credentials/indexer-web.service/admin-key";
        };

        systemd.services.indexer-web-secret-key = {
          description = "Generate indexer-web admin API key (machine-local random)";
          wantedBy = [ "multi-user.target" ];
          before = [ "indexer-web.service" ];
          serviceConfig = lib.mkMerge [
            (harden { })
            (serviceOneshotDefaults { })
            {
              Type = "oneshot";
              StateDirectory = "indexer-web-keys";
              ExecStart = lib.getExe generateAdminKey;
            }
          ];
        };

        systemd.services.indexer-web = {
          inherit onFailure;
          startLimitBurst = 5;
          startLimitIntervalSec = 300;
          requires = [ "indexer-web-secret-key.service" ];
          after = [ "indexer-web-secret-key.service" ];
          serviceConfig = lib.mkMerge [
            {
              # /home/<user> is 0700: upstream's DynamicUser (plain value)
              # can never traverse the scan roots. primaryUser + upstream's
              # ProtectHome=read-only (mr-sync posture). mkForce beats the
              # upstream plain declaration (CPUQuota trap).
              User = lib.mkForce primaryUser;
              DynamicUser = lib.mkForce false;
              MemoryMax = "1G";
              LoadCredential = [ "admin-key:${adminKeyPath}" ];
              # The binary's OTel wiring (see header). Registry-set
              # OTEL_EXPORTER_OTLP_ENDPOINT merges beside it.
              Environment = [ "INDEXERWEB_OTEL_ENDPOINT=http://localhost:4318" ];
            }
            (harden { MemoryMax = "1G"; })
          ];
        };

        # Service-integration registry entry (modules/nixos/services/
        # integration.nix): ONE declaration fans out to the Caddy vHost
        # (Layer 2 protected), Gatus checks, dashboard tile, system-health
        # monitoring, and the OTel wiring (env + signoz-coverage + endpoint
        # audit). No backup (state is rebuildable from a rescan), no OIDC
        # client (the protected layer owns external auth).
        services.integration = lib.optionalAttrs (options ? services.integration) {
          indexer-web = {
            subdomain = "index";
            port = ports.indexer-web;
            vHost.layer = "protected";
            otel = {
              serviceName = "indexer-web";
              # The binary parses the endpoint as a URL (WithEndpointURL) —
              # scheme required, hence http-url not http-host-port.
              shape = "http-url";
              maxAgeHours = 720;
            };
            checks = [
              {
                name = "Indexer Web";
                group = "Development";
                path = "/";
                interval = "1m";
                conditions = [
                  "[STATUS] == 200"
                  "[BODY] == pat(*<html*)"
                ];
              }
              {
                name = "Indexer Web Metrics";
                group = "Development";
                path = "/metrics";
                interval = "5m";
                conditions = [
                  "[STATUS] == 200"
                  "[BODY] == pat(*indexer_scan_in_progress*)"
                ];
              }
            ];
            homepage = {
              name = "index";
              group = "Development";
              description = "Project docs index";
              icon = "mdi-file-table-box-multiple-outline";
            };
            monitored = true;
          };
        };
      };
    };
}
