# OpenSEO self-hosted SEO suite (keyword research, rank tracking, audits)
# Native NixOS service — builds from source, no Docker container.
# SSO: no built-in auth (AUTH_MODE=local_noauth). Access is gated by
# oauth2-proxy forward-auth (Layer 2 SSO) on seo.<domain>.
#
# Optional features (declarative via module options):
#   - Google Search Console: services.openseo.googleSearchConsole.enable
#     Requires google_client_id, google_client_secret, better_auth_secret in openseo.yaml.
#     GSC OAuth callback at https://seo.<domain>/api/gsc/oauth/callback works behind
#     protectedVHost because the browser carries the oauth2-proxy session cookie.
#   - AI agent (SAM): services.openseo.aiFeatures.enable
#     Requires openrouter_api_key in openseo.yaml.
_: {
  flake.nixosModules.openseo =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    let
      cfg = config.services.openseo;
      inherit (config.networking) domain;
      libHelpers = import ../../../lib/default.nix lib;
      inherit (libHelpers)
        harden
        serviceDefaults
        onFailure
        serviceTypes
        ports
        ;

      pkg = pkgs.openseo;
      stateDir = "/var/lib/openseo";
      storeDir = "${pkg}/lib/openseo";

      # Stage: symlink read-only project files from Nix store into a writable
      # project directory, preserving the persistent .wrangler state dir.
      stageScript = pkgs.writeShellScriptBin "openseo-stage" ''
        set -euo pipefail
        PROJECT="${stateDir}/project"
        STORE="${storeDir}"

        mkdir -p "$PROJECT" "${stateDir}/.wrangler"

        # Remove old symlinks (preserves .wrangler which is a real dir at stateDir)
        find "$PROJECT" -maxdepth 1 -type l -delete

        # Symlink all files and dotfiles from the Nix store.
        # node_modules is handled separately below — it needs a writable .vite-temp.
        for item in "$STORE"/* "$STORE"/.[!.]*; do
          [ -e "$item" ] || continue
          name="$(basename "$item")"
          [ "$name" = "node_modules" ] && continue
          ln -s "$item" "$PROJECT/$name"
        done

        # node_modules: Vite's config loader (loadConfigFromBundledFile) writes
        # a temp .mjs bundle into node_modules/.vite-temp/. A plain symlink to
        # the read-only Nix store node_modules makes vite preview crash with
        # EROFS. Replace it with a real directory that re-points each top-level
        # package to the store, plus a writable .vite-temp. rm -rf handles both
        # the fresh symlink (from the loop above) and a real dir (prior run).
        rm -rf "$PROJECT/node_modules"
        mkdir -p "$PROJECT/node_modules/.vite-temp"
        for item in "$STORE/node_modules"/* "$STORE/node_modules"/.[!.]*; do
          [ -e "$item" ] || continue
          name="$(basename "$item")"
          [ "$name" = ".vite-temp" ] && continue
          ln -s "$item" "$PROJECT/node_modules/$name"
        done

        # Link .wrangler to persistent state directory (writable D1 SQLite)
        ln -sfn "${stateDir}/.wrangler" "$PROJECT/.wrangler"

        # Seed deploy config from build output (generated by @cloudflare/vite-plugin
        # during vite build). vite preview reads .wrangler/deploy/config.json at
        # startup — it's static worker config, not runtime state.
        if [ -f "${storeDir}/.wrangler/deploy/config.json" ] && \
           [ ! -f "${stateDir}/.wrangler/deploy/config.json" ]; then
          mkdir -p "${stateDir}/.wrangler/deploy"
          cp "${storeDir}/.wrangler/deploy/config.json" "${stateDir}/.wrangler/deploy/config.json"
        fi
      '';

      # Migrate: apply D1 (SQLite) migrations locally
      migrateScript = pkgs.writeShellScriptBin "openseo-migrate" ''
        set -euo pipefail
        cd "${stateDir}/project"
        exec "${storeDir}/node_modules/.bin/wrangler" d1 migrations apply DB --local
      '';

      # Serve: vite preview must run from the staged project directory.
      # Wrapped because systemd's WorkingDirectory is the state dir
      # (the project subdir doesn't exist until ExecStartPre creates it).
      serveScript = pkgs.writeShellScriptBin "openseo-serve" ''
        cd "${stateDir}/project"
        exec "${storeDir}/node_modules/.bin/vite" preview --host 127.0.0.1 --port ${toString cfg.port}
      '';
    in
    {
      options.services.openseo = {
        enable = lib.mkEnableOption "OpenSEO — self-hosted SEO suite (keyword research, rank tracking, backlinks, site audits)";
        port = serviceTypes.servicePort ports.openseo "HTTP port for OpenSEO dashboard";

        googleSearchConsole = {
          enable = lib.mkEnableOption ''
            Google Search Console integration.
            Requires google_client_id, google_client_secret, and better_auth_secret
            in the openseo.yaml sops file. The GSC OAuth callback at
            /api/gsc/oauth/callback works behind protectedVHost (browser carries
            the oauth2-proxy session cookie).
          '';
        };

        aiFeatures = {
          enable = lib.mkEnableOption ''
            AI features (SAM in-app SEO agent via OpenRouter).
            Requires openrouter_api_key in the openseo.yaml sops file.
          '';
        };
      };

      config = lib.mkIf cfg.enable {
        users.users.openseo = {
          isSystemUser = true;
          group = "openseo";
          home = stateDir;
        };
        users.groups.openseo = { };

        systemd.services.openseo = {
          description = "OpenSEO — self-hosted SEO suite";
          inherit onFailure;
          wantedBy = [ "multi-user.target" ];
          after = [
            "network.target"
            "sops-nix.service"
          ];
          wants = [ "sops-nix.service" ];
          path = [ pkgs.nodejs ];
          startLimitBurst = 5;
          startLimitIntervalSec = 300;

          # restartTriggers: prevent stale vite preview process serving GC'd static
          # files from the old nix store path. Same pattern as homepage-dashboard.
          restartTriggers = [ pkg ];

          serviceConfig = lib.mkMerge [
            (harden {
              MemoryMax = "2G";
            })
            (serviceDefaults { })
            {
              User = "openseo";
              Group = "openseo";
              StateDirectory = "openseo";
              WorkingDirectory = "${stateDir}";
              EnvironmentFile = config.sops.templates."openseo-env".path;

              Environment = [
                "PORT=${toString cfg.port}"
                "AUTH_MODE=local_noauth"
                "ALLOWED_HOST=seo.${domain}"
                "VITE_SHOW_DEVTOOLS=false"
                "NODE_OPTIONS=--max-old-space-size=1536"
                "CLOUDFLARE_INCLUDE_PROCESS_ENV=true"
                "HOME=${stateDir}"
                # Privacy: opt out of OpenSEO's anonymous telemetry (introduced v0.1.0).
                # Sends heartbeats with aggregate counts every 5 min during first 2h,
                # then at most once daily. No personal data, but unnecessary for a
                # self-hosted homelab.
                "OPENSEO_TELEMETRY_DISABLED=1"
              ];

              ExecStartPre = [
                (lib.getExe stageScript)
                (lib.getExe migrateScript)
              ];
              ExecStart = lib.getExe serveScript;
            }
          ];
        };
      };
    };
}
