#!/usr/bin/env bash
set -euo pipefail

# SystemNix Status Report Generator
# Generates a comprehensive status report similar to manual status docs

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S %Z")
HOSTNAME=$(hostname)
REPORT_FILE="docs/status/$(date +%Y-%m-%d_%H-%M)-STATUS.md"

echo "Generating status report: $REPORT_FILE"

# Create the report
cat > "$REPORT_FILE" <<HEADER
# Status Report — $TIMESTAMP

**Host:** $HOSTNAME

---

## System Info

HEADER

# NixOS or macOS
if command -v nixos-version >/dev/null 2>&1; then
    echo "- **OS:** NixOS $(nixos-version 2>/dev/null || true)" >> "$REPORT_FILE"
    echo "- **Uptime:** $(uptime -p 2>/dev/null || uptime | awk -F',' '{print $1}')" >> "$REPORT_FILE"
else
    echo "- **OS:** macOS $(sw_vers -productVersion 2>/dev/null || echo 'unknown')" >> "$REPORT_FILE"
fi

echo "- **Kernel:** $(uname -r)" >> "$REPORT_FILE"
echo "- **Architecture:** $(uname -m)" >> "$REPORT_FILE"

# Disk usage
echo "" >> "$REPORT_FILE"
echo "## Disk Usage" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
df -h / 2>/dev/null | tail -1 >> "$REPORT_FILE" || true
echo '```' >> "$REPORT_FILE"

# Memory
echo "" >> "$REPORT_FILE"
echo "## Memory" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
free -h 2>/dev/null || echo "Memory info unavailable" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"

# Git status
echo "" >> "$REPORT_FILE"
echo "## Git" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "**Branch:** $(git branch --show-current 2>/dev/null || echo 'unknown')" >> "$REPORT_FILE"
echo "**Status:** $(git status --short | wc -l) modified file(s)" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "**Recent commits:**" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
git log --oneline -10 2>/dev/null >> "$REPORT_FILE" || true
echo '```' >> "$REPORT_FILE"

# Services (Linux only)
if [[ "$(uname)" == "Linux" ]]; then
    echo "" >> "$REPORT_FILE"
    echo "## Services" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo "| Service | Status |" >> "$REPORT_FILE"
    echo "|---------|--------|" >> "$REPORT_FILE"

    for svc in caddy forgejo immich signoz gatus hermes manifest openseo pocket-id oauth2-proxy dnsblockd unbound niri; do
        status=$(systemctl is-active "$svc" 2>/dev/null || echo "unknown")
        if [ "$status" = "active" ]; then
            echo "| $svc | ✅ $status |" >> "$REPORT_FILE"
        elif [ "$status" = "inactive" ]; then
            echo "| $svc | ⚠️ $status |" >> "$REPORT_FILE"
        else
            echo "| $svc | ❓ $status |" >> "$REPORT_FILE"
        fi
    done

    # User services
    echo "" >> "$REPORT_FILE"
    echo "### User Services" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo "| Service | Status |" >> "$REPORT_FILE"
    echo "|---------|--------|" >> "$REPORT_FILE"

    for svc in waybar emeet-pixyd; do
        status=$(systemctl --user is-active "$svc" 2>/dev/null || echo "unknown")
        if [ "$status" = "active" ]; then
            echo "| $svc | ✅ $status |" >> "$REPORT_FILE"
        elif [ "$status" = "inactive" ]; then
            echo "| $svc | ⚠️ $status |" >> "$REPORT_FILE"
        else
            echo "| $svc | ❓ $status |" >> "$REPORT_FILE"
        fi
    done
fi

# Nix store info
echo "" >> "$REPORT_FILE"
echo "## Nix Store" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "- **Store size:** $(du -sh /nix/store 2>/dev/null | cut -f1 || echo 'unknown')" >> "$REPORT_FILE"
echo "- **Generations:** $(sudo nix-env --list-generations --profile /nix/var/nix/profiles/system 2>/dev/null | wc -l || echo 'unknown')" >> "$REPORT_FILE"

# Flake check
echo "" >> "$REPORT_FILE"
echo "## Build Status" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
if nix flake check --no-build 2>&1 | tail -5 >> "$REPORT_FILE"; then
    echo '```' >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo "✅ **Flake check passed**" >> "$REPORT_FILE"
else
    echo '```' >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo "❌ **Flake check failed**" >> "$REPORT_FILE"
fi

echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "*Auto-generated by \`just status\`*" >> "$REPORT_FILE"

echo ""
echo "Status report generated: $REPORT_FILE"
